---
## install ansible packages

- name: install system packages for ansible
  block:
    - name: install system packages (will update if it fails)
      apt:
        name: "{{ dev_ansible_system_packages }}"
      become: true
      ## reduce long error message
      no_log: "{{ hide_secrets |bool }}"
  rescue:
    - name: install system packages (update cache)
      apt:
        name: "{{ dev_ansible_system_packages }}"
        update_cache: true
      become: true

- name: upload pip requirements
  copy:
    src: requirements.txt
    dest: "{{ dev_ansible_package_list }}"
    force: true
    mode: 0644

- name: check that ansible is installed
  stat:
    path: "{{ dev_ansible_dir }}/site-packages/ansible/__init__.py"
  register: stat_ansible_package

- name: setup virtual environment
  import_tasks: venv.yml
  when: not stat_ansible_package.stat.exists
...
