---
## convenient links for user-local ansible binaries

- name: expand home directory in parameters
  set_fact:
    bin_dir: "{{ dev_ansible_dir |expanduser }}/bin"
    link_dir: "{{ dev_ansible_link_dir |expanduser }}"

- name: directory for links to ansible binaries
  file:
    path: "{{ link_dir }}"
    state: directory
    mode: 0755
  register: link_dir_result

- name: links for ansible-prefixed binaries
  shell: >
    for bin in ansible-* ; do
      ln -s -f \
        "{{ bin_dir | relpath(link_dir) }}/$bin" \
        "{{ link_dir }}/"
    done
  args:
    chdir: "{{ bin_dir }}"
    creates: "{{ link_dir }}/ansible-playbook"

- name: links for ansible flavored pip, python etc
  file:
    state: link
    src: "{{ bin_dir | relpath(link_dir) }}/{{ item.0 }}"
    dest: "{{ link_dir }}/{{ item.1 }}"
  loop: "{{ dev_ansible_linked_binaries }}"
  loop_control:
    label: "{{ item.1 }}"
...
