---
# tasks file for dev-ivansible

- block:
    - name: install system packages
      apt:
        name: "{{ dev_ansible_system_packages }}"
      become: true

    - name: upload pip requirements
      copy:
        src: requirements.txt
        dest: "{{ dev_ansible_package_list }}"
        mode: 0644
      register: pip_requirements_result

    - name: setup virtual environment
      pip:
        requirements: "{{ dev_ansible_package_list }}"
        virtualenv: "{{ dev_ansible_dir }}"
        virtualenv_python: "{{ dev_ansible_python }}"
      when: pip_requirements_result is changed
  tags: dev_ansible_venv


- block:
    - name: expand home directory in parameters
      set_fact:
        bin_dir: "{{ dev_ansible_dir |expanduser }}/bin"
        link_dir: "{{ dev_ansible_link_dir |expanduser }}"

    - name: directory for links to ansible binaries
      file:
        path: "{{ link_dir }}"
        state: directory
      register: link_dir_result

    - name: links for ansible binaries
      shell: >
        for bin in ansible* ; do
          ln -sf \
            "{{ bin_dir | relpath(link_dir) }}/$bin" \
            "{{ link_dir }}/"
        done
      args:
        chdir: "{{ bin_dir }}"
        creates: "{{ link_dir }}/ansible-playbook"

    - name: links for ansible flavored pip and python
      file:
        state: link
        src: "{{ bin_dir | relpath(link_dir) }}/{{ item }}"
        dest: "{{ link_dir }}/ansible-{{ item }}"
      loop:
        - pip
        - python

  when: "dev_ansible_link_dir != ''"
  tags: dev_ansible_links


- block:
    - name: add link directory on the path
      lineinfile:
        # path file must correspond with role ivansible.dev_user
        # https://github.com/ivansible/dev-user/blob/master/tasks/bashrc.yml
        path: ~/.local/bashrc/2path.sh
        line: "export PATH={{ dev_ansible_link_dir }}:$PATH"
        state: present
      when: "dev_ansible_link_dir != ''"

    - name: alias for ansible-playbook
      lineinfile:
        path: ~/.local/bashrc/4alias.sh
        line: "alias ap='ansible-playbook'"

  when: "dev_ansible_update_bashrc |bool"
  tags: dev_ansible_bashrc
...
