---
- name: tasks for dev-ansible role
  block:
    - name: install ansible packages
      import_tasks: install.yml
      tags: dev_ansible_install

    - name: workaround for old ansible pre-installed on vagrant
      import_tasks: old.yml
      tags: dev_ansible_upgrade

    - name: apply patches to ansible, mitogen and molecule
      import_tasks: patch.yml
      ## detection task produces no output in check mode
      when:
        - not ansible_check_mode
        - dev_ansible_apply_patches |bool
      tags: dev_ansible_patch

    - name: convenient links for user-local ansible binaries
      import_tasks: links.yml
      when: dev_ansible_link_dir |d('')
      tags: dev_ansible_links

    - name: convenient ansible aliases in users profile
      import_tasks: aliases.yml
      when: dev_ansible_update_bashrc |bool
      tags: dev_ansible_bashrc
  tags: dev_ansible_all
...
