---
## setup virtual environment for ansible

- name: create virtual environment
  command:
    argv:
      - "{{ dev_ansible_python }}"
      - -m
      - venv
      - "{{ dev_ansible_dir }}"
    creates: "{{ dev_ansible_dir }}"
  register: _dev_ansible_venv_create

- name: fix setuptools version on xenial, prevent syntax error
  pip:
    name:
      - pip==20.3.3         # pip 21 will deprecate python 3.5
      - setuptools==50.3.2  # setuptools 51.3.x triggers syntax error
      - wheel==0.36.2       # this version has been tested and approved
    virtualenv: "{{ dev_ansible_dir }}"
    virtualenv_python: "{{ dev_ansible_python }}"
  when: ansible_lsb.codename == 'xenial'

- name: upgrade to latest setuptools on bionic+
  pip:
    name: pip,setuptools,wheel
    state: latest  # noqa 403
  when:
    - ansible_lsb.codename != 'xenial'
    - _dev_ansible_venv_create is changed

- name: setup virtual environment
  pip:
    requirements: "{{ dev_ansible_package_list }}"
    virtualenv: "{{ dev_ansible_dir }}"
    virtualenv_python: "{{ dev_ansible_python }}"
  when: not stat_ansible_package.stat.exists
...
